export const FEATURE_FLAGS = {
  ENABLE_DOPPLER_RADAR: true,
  ENABLE_CYCLONE_TRACKER: true,
  ENABLE_LIGHTNING_ALERT: true,
  ENABLE_AGROMET_ADVISORY: true,
  ENABLE_AVIATION_METAR: true,
  ENABLE_SOLAR_ESTIMATOR: true,
  ENABLE_WEATHER_GPT_VOICE: true,
  ENABLE_CROWDSOURCING: true,
  ENABLE_ROUTE_NOWCAST: true,
  ENABLE_AIR_QUALITY_INDEX: true,
  ENABLE_OFFLINE_CACHE: true,
};
